name: ci
on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: langston-barrett/gha/.github/workflows/rust-ci.yml@d0cdf249a9684185d96083c87d078679cd373b28
    with:
      bench: false
      os: ubuntu-latest