name: ci
on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: langston-barrett/gha/.github/workflows/rust-ci.yml@6292a6a380c64b0d40ee22384fb96d21bc74667c
    with:
      bench: false
      os: ubuntu-latest