name: ci
on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: langston-barrett/gha/.github/workflows/rust-ci.yml@e301defafac5610638fe6b6b6afb867557d02f0a
    with:
      bench: false
      os: ubuntu-latest